# -*- coding: utf-8 -*-
"""Model save

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmik8wx5QsYOZVV0rZSNpiV0mOyZ7CyB
"""

model.save('gesture.h5')