# -*- coding: utf-8 -*-
"""Image data generator library

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmik8wx5QsYOZVV0rZSNpiV0mOyZ7CyB
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator