# -*- coding: utf-8 -*-
"""Configureimagedatagenerator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmik8wx5QsYOZVV0rZSNpiV0mOyZ7CyB
"""

train_datagen = ImageDataGenerator(rescale=1./255,
                                   shear_range=0.2,
                                   zoom_range=0.2,
                                   horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)