# -*- coding: utf-8 -*-
"""compile

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmik8wx5QsYOZVV0rZSNpiV0mOyZ7CyB
"""

model.compile(optimizer='adam',loss=losses.categorical_crossentropy,metrics=['accuracy'])